POST http://localhost:8080/api/players
Content-Type: application/json

{
  "name": "Gulácsi Péter",
  "birthDate": "1990-10-10",
  "position":"LEFT_FULLBACK"
}

###

GET http://localhost:8080/api/players
Accept: application/json

###
